CREATE TABLE quiz (
    id INT PRIMARY KEY AUTO_INCREMENT,
    cate VARCHAR(50) NOT NULL,
    subcate VARCHAR(50),
    quiz TEXT NOT NULL,
    ans TEXT NOT NULL
);

CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL
);
